#ifndef _DEFINITIONS_FOR_CUDA_RADAR_2016_HH
#define _DEFINITIONS_FOR_CUDA_RADAR_2016_HH

#define _USE_MATH_DEFINES

#define RAWDATAVISUALIZATION
#define THREADSPERBLOCK 1024
#define MAXBLOBS 2048

#define INPUTFILENAME "radarData.tur"

#define MESHWIDTH 4096	
#define MESHHEIGHT 4096
#endif